[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "git_cluster"
version = "0.2.3"
description = "An enhanced version of the GIT (Graph Intensity Topology) ğŸŒ clustering algorithm, repackaged ğŸ“¦ for optimal ease of use ğŸ› ï¸."
authors = ["LABRIJI Saad <labrijisaad@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/labrijisaad/Git-Clustering"
repository = "https://github.com/labrijisaad/Git-Clustering"
documentation = "https://github.com/gaozhangyang/GIT#readme"
keywords = ["GIT_clustering", "clustering", "graph-intensity-topology", "data-science"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3.11",
]
packages = [
    { include = "git_cluster", from = "src" },
    { include = "dataloaders", from = "src" },
    { include = "utils", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.8.0"
numpy = "^1.22.2"
scipy = "^1.8.0"
scikit-learn = "^1.2.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^22.1.0"
isort = "^5.10.1"

[tool.poetry.urls]
"Homepage" = "https://github.com/labrijisaad/Git-Clustering"
"Repository" = "https://github.com/labrijisaad/Git-Clustering"
"Documentation" = "https://github.com/gaozhangyang/GIT#readme"